pvpbot-enabled: false
give-mystery-box-on-vote: false
enable-vote-ranks: false
block-chorus-fruit: true
block-explosion-block-damage: true
#world:customname
worlds:
   world: 'World'
   world_the_end: 'End'
   world_nether: 'Nether'
   donor: 'Donor'

voteranks:
   beginner: 50
   regular: 100
   advanced: 180
   epic: 300
   master: 550
   tryhard: 920
   legend: 1500
